# Generated by Django 5.1.7 on 2026-07-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='full_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
